name: Apply

permissions: write-all

on:
  workflow_dispatch:
    inputs:
      account_id:
        type: string
        required: true
        default: 541792499640
      environment:
        type: string
        required: true
        default: prod
      expires_after:
        type: string
        required: false
        default: "1 day"
      region:
        type: string
        required: true
        default: eu-central-1
      tfvars:
        type: string
        required: false
        default: ""

jobs:
  apply:
    uses: stormreply/terraform-workflow-controller/.github/workflows/apply.yaml@main
    with:
      account_id: ${{ inputs.account_id }}
      environment: ${{ inputs.environment }}
      expires_after: ${{ inputs.expires_after }}
      region: ${{ inputs.region }}
      tfvars: ${{ inputs.tfvars }}
    secrets: inherit
