name: Apply

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:
    # checkov:skip=CKV_GHA_7: "GitHub Actions workflow_dispatch inputs MUST be empty"
    inputs:
      lifetime:
        type: string
        required: false
        default: 1 day
      delay:
        type: string
        required: false
        default: ""
      environment:
        type: string
        required: false
        default: ""

jobs:

  apply:
    uses: stormreply/storm-library-for-terraform/.github/workflows/apply.yaml@main
    with:
      lifetime: ${{ inputs.lifetime }}
      delay: ${{ inputs.delay }}
      environment: ${{ inputs.environment }}
    secrets:
      STORM_LIBRARY_FOR_TERRAFORM: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
      TERRAFORM_PRIVATE_KEY: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
