name: Apply

permissions: write-all

on:
  workflow_dispatch:
    inputs:
      region:
        type: string
        required: true
        default: eu-central-1
      expires_after:
        type: string
        required: false
        default: "1 day"
      environment:
        type: string
        required: false
        default: ""
      var_file:
        type: string
        required: false
        default: ""

jobs:
  apply:
    uses: stormreply/storm-library-for-terraform/.github/workflows/apply.yaml@main
    with:
      environment: ${{ inputs.environment }}
      expires_after: ${{ inputs.expires_after }}
      region: ${{ inputs.region }}
      var_file: ${{ inputs.tfvars }}
    secrets: inherit
