name: Destroy

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: false
        default: ""
      var_file:
        type: string
        required: false
        default: ""
  workflow_dispatch:
    # checkov:skip=CKV_GHA_7: "GitHub Actions workflow_dispatch inputs MUST be empty"
    inputs:
      environment:
        type: string
        required: false
        default: ""
      var_file:
        type: string
        required: false
        default: ""

jobs:
  destroy:
    uses: stormreply/storm-library-for-terraform/.github/workflows/destroy.yaml@main
    secrets: inherit
    with:
      environment: ${{inputs.environment}}
      var_file: ${{inputs.var_file}}
