name: Destroy

permissions:
  contents: read
  id-token: write

on:

  workflow_dispatch:
    # checkov:skip=CKV_GHA_7: "GitHub Actions workflow_dispatch inputs MUST be empty"
    inputs:
      delay:
        type: string
        required: false
        default: ""
      environment:
        type: string
        required: false
        default: ""

jobs:
  destroy:
    uses: stormreply/storm-library-for-terraform/.github/workflows/destroy.yaml@main
    with:
      environment: ${{ inputs.environment }}
      delay: ${{ inputs.delay }}
    secrets:
      STORM_LIBRARY_FOR_TERRAFORM: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
      TERRAFORM_PRIVATE_KEY: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
