name: Destroy

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:

jobs:
  destroy:
    uses: stormreply/storm-library-for-terraform/.github/workflows/destroy.yaml@main
    secrets: inherit
