name: Destroy

permissions: write-all

on:
  workflow_dispatch:
    inputs:
      account_id:
        type: string
        required: true
        default: 541792499640
      region:
        type: string
        required: true
        default: eu-central-1
      environment:
        type: string
        required: false
        default: ""
      var_file:
        type: string
        required: false
        default: ""

jobs:
  destroy:
    uses: stormreply/terraform-workflow-controller/.github/workflows/destroy.yaml@main
    with:
      account_id: ${{ inputs.account_id }}
      environment: ${{ inputs.environment }}
      region: ${{ inputs.region }}
      var_file: ${{ inputs.tfvars }}
    secrets: inherit