name: Plan

permissions: write-all

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: false
        default: ""
      var_file:
        type: string
        required: false
        default: ""

jobs:
  plan:
    uses: stormreply/storm-library-for-terraform/.github/workflows/plan.yaml@main
    with:
      environment: ${{ inputs.environment }}
      var_file: ${{ inputs.tfvars }}
    secrets: inherit
