name: Set backend

permissions:
  read-all

on:
  workflow_dispatch:
    # checkov:skip=CKV_GHA_7: "GitHub Actions workflow_dispatch inputs MUST be empty"
    inputs:
      backend_account:
        required: false
      backend_region:
        required: false

jobs:

  set-backend:
    uses: stormreply/storm-library-for-terraform/.github/workflows/set-backend.yaml@main
    with:
      backend_account: ${{ inputs.backend_account || vars.BACKEND_ACCOUNT }}
      backend_region: ${{ inputs.backend_region || vars.BACKEND_REGION }}
    secrets:
      STORM_LIBRARY_FOR_TERRAFORM: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
