name: Test

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:

jobs:
  test:
    uses: stormreply/storm-library-for-terraform/.github/workflows/test.yaml@main
    secrets:
      STORM_LIBRARY_FOR_TERRAFORM: ${{ secrets.STORM_LIBRARY_FOR_TERRAFORM }}
      TERRAFORM_PRIVATE_KEY: ${{ secrets.TERRAFORM_PRIVATE_KEY }}
